// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZfa5gTFBLtSUUR9xwYHLXYTU1djF5304',
    appId: '1:455212530294:web:0807d2fb0ae5084305bd57',
    messagingSenderId: '455212530294',
    projectId: 'authtutorial-fd1b5',
    authDomain: 'authtutorial-fd1b5.firebaseapp.com',
    storageBucket: 'authtutorial-fd1b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf7MGwUReD2V80HhTEF6AEB-bALYdV2ts',
    appId: '1:455212530294:android:b5135dc1af95387805bd57',
    messagingSenderId: '455212530294',
    projectId: 'authtutorial-fd1b5',
    storageBucket: 'authtutorial-fd1b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVdhrarn60BCphi32h4tiVqF-xH1sTFT4',
    appId: '1:455212530294:ios:2d86a77ef8ec16c605bd57',
    messagingSenderId: '455212530294',
    projectId: 'authtutorial-fd1b5',
    storageBucket: 'authtutorial-fd1b5.appspot.com',
    iosClientId: '455212530294-2jd1r5e3t40k773nkjqji9e7pnnm020u.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernLoginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVdhrarn60BCphi32h4tiVqF-xH1sTFT4',
    appId: '1:455212530294:ios:f263f6457974641405bd57',
    messagingSenderId: '455212530294',
    projectId: 'authtutorial-fd1b5',
    storageBucket: 'authtutorial-fd1b5.appspot.com',
    iosClientId: '455212530294-9hfdq46abudal1tk518hbbnkleq6jebq.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernLoginUi.RunnerTests',
  );
}
